/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CookieHeading {
    }
    interface CookieIconList {
    }
    interface CookieIconListItem {
        "accessibleLabel": string;
        "icon": string;
        "url": string;
    }
    interface CookieLink {
        "accessibleLabel": string;
        "external": boolean;
        "url": string;
    }
    interface CookieList {
    }
    interface CookieListItem {
    }
    interface CookieLogo {
        "url": string;
    }
    interface CookieParagraph {
    }
    interface CookieSection {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCookieHeadingElement extends Components.CookieHeading, HTMLStencilElement {
    }
    var HTMLCookieHeadingElement: {
        prototype: HTMLCookieHeadingElement;
        new (): HTMLCookieHeadingElement;
    };
    interface HTMLCookieIconListElement extends Components.CookieIconList, HTMLStencilElement {
    }
    var HTMLCookieIconListElement: {
        prototype: HTMLCookieIconListElement;
        new (): HTMLCookieIconListElement;
    };
    interface HTMLCookieIconListItemElement extends Components.CookieIconListItem, HTMLStencilElement {
    }
    var HTMLCookieIconListItemElement: {
        prototype: HTMLCookieIconListItemElement;
        new (): HTMLCookieIconListItemElement;
    };
    interface HTMLCookieLinkElement extends Components.CookieLink, HTMLStencilElement {
    }
    var HTMLCookieLinkElement: {
        prototype: HTMLCookieLinkElement;
        new (): HTMLCookieLinkElement;
    };
    interface HTMLCookieListElement extends Components.CookieList, HTMLStencilElement {
    }
    var HTMLCookieListElement: {
        prototype: HTMLCookieListElement;
        new (): HTMLCookieListElement;
    };
    interface HTMLCookieListItemElement extends Components.CookieListItem, HTMLStencilElement {
    }
    var HTMLCookieListItemElement: {
        prototype: HTMLCookieListItemElement;
        new (): HTMLCookieListItemElement;
    };
    interface HTMLCookieLogoElement extends Components.CookieLogo, HTMLStencilElement {
    }
    var HTMLCookieLogoElement: {
        prototype: HTMLCookieLogoElement;
        new (): HTMLCookieLogoElement;
    };
    interface HTMLCookieParagraphElement extends Components.CookieParagraph, HTMLStencilElement {
    }
    var HTMLCookieParagraphElement: {
        prototype: HTMLCookieParagraphElement;
        new (): HTMLCookieParagraphElement;
    };
    interface HTMLCookieSectionElement extends Components.CookieSection, HTMLStencilElement {
    }
    var HTMLCookieSectionElement: {
        prototype: HTMLCookieSectionElement;
        new (): HTMLCookieSectionElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "cookie-heading": HTMLCookieHeadingElement;
        "cookie-icon-list": HTMLCookieIconListElement;
        "cookie-icon-list-item": HTMLCookieIconListItemElement;
        "cookie-link": HTMLCookieLinkElement;
        "cookie-list": HTMLCookieListElement;
        "cookie-list-item": HTMLCookieListItemElement;
        "cookie-logo": HTMLCookieLogoElement;
        "cookie-paragraph": HTMLCookieParagraphElement;
        "cookie-section": HTMLCookieSectionElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CookieHeading {
    }
    interface CookieIconList {
    }
    interface CookieIconListItem {
        "accessibleLabel"?: string;
        "icon"?: string;
        "url"?: string;
    }
    interface CookieLink {
        "accessibleLabel"?: string;
        "external"?: boolean;
        "url"?: string;
    }
    interface CookieList {
    }
    interface CookieListItem {
    }
    interface CookieLogo {
        "url"?: string;
    }
    interface CookieParagraph {
    }
    interface CookieSection {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "cookie-heading": CookieHeading;
        "cookie-icon-list": CookieIconList;
        "cookie-icon-list-item": CookieIconListItem;
        "cookie-link": CookieLink;
        "cookie-list": CookieList;
        "cookie-list-item": CookieListItem;
        "cookie-logo": CookieLogo;
        "cookie-paragraph": CookieParagraph;
        "cookie-section": CookieSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cookie-heading": LocalJSX.CookieHeading & JSXBase.HTMLAttributes<HTMLCookieHeadingElement>;
            "cookie-icon-list": LocalJSX.CookieIconList & JSXBase.HTMLAttributes<HTMLCookieIconListElement>;
            "cookie-icon-list-item": LocalJSX.CookieIconListItem & JSXBase.HTMLAttributes<HTMLCookieIconListItemElement>;
            "cookie-link": LocalJSX.CookieLink & JSXBase.HTMLAttributes<HTMLCookieLinkElement>;
            "cookie-list": LocalJSX.CookieList & JSXBase.HTMLAttributes<HTMLCookieListElement>;
            "cookie-list-item": LocalJSX.CookieListItem & JSXBase.HTMLAttributes<HTMLCookieListItemElement>;
            "cookie-logo": LocalJSX.CookieLogo & JSXBase.HTMLAttributes<HTMLCookieLogoElement>;
            "cookie-paragraph": LocalJSX.CookieParagraph & JSXBase.HTMLAttributes<HTMLCookieParagraphElement>;
            "cookie-section": LocalJSX.CookieSection & JSXBase.HTMLAttributes<HTMLCookieSectionElement>;
        }
    }
}
